using SdmFramework.Model;
using SdmFramework.Resource.Visitor.Helper;

namespace SdmFramework.Service.ViewEngine.Compiler.Visitor;

/// <summary>
/// Visitor class for processing the abstract syntax tree generated by the Razor parser.
/// returns a HTML format string
/// </summary>
public class SdmVisitor : BasicRazorBaseVisitor<object?>
{
    private Dictionary<string, object?> Variables { get; } = new();
    private object _model;
    private ModelWrapper _modelWrapper;
    private object? CurrentValue;

    public SdmVisitor(object model)
    {
        _model = model;
        if (model != null)
        {
            _modelWrapper = new ModelWrapper(_model);
        }
    }
    
    public override object? VisitModelDeclaration(BasicRazorParser.ModelDeclarationContext context)
    {
        return "";
    }

    public override object? VisitTextContent(BasicRazorParser.TextContentContext context)
    {
        string contentResult = "";
            
        foreach (var id in context.ID())
        {
            contentResult += " " + id;
        }
        return contentResult.Trim();
    }

    public override string VisitModelDataExpression(BasicRazorParser.ModelDataExpressionContext context)
    {
        string propertyName = context.ID().ToString();
        //Console.WriteLine($"property name: {propertyName}");

        if (_modelWrapper.ModelInstance != null)
        {
            return _modelWrapper.GetPropertyValue(propertyName).ToString() ?? "Property not found";
        }
        else
        {
            throw new InvalidOperationException("Model is null");
        }
    }

    public override object? VisitForeachStatement(BasicRazorParser.ForeachStatementContext context)
    {
        string contentResult = "";
        if (context.modelForExpression().GetText() == "Model")
        {
            if (_modelWrapper.ModelInstance is IEnumerable<object> modelCollection)
            
                foreach (var item in modelCollection)
                {
                    CurrentValue = item;
                    foreach (var block in context.blockContent())
                    {
                        contentResult += Visit(block).ToString();
                        
                        
                    }
                }
        }
        else if (context.modelForExpression().ID() != null)
        {
            var collectionName = context.modelForExpression().ID().ToString();
            IEnumerable<object> collection = _modelWrapper.GetPropertyValue(collectionName) as IEnumerable<object>;
            foreach (var item in collection)
            {
                CurrentValue = item;
                foreach (var blockContentContext in context.blockContent()) Visit(blockContentContext);
            }
        }

        CurrentValue = null;
        return contentResult;
    }

    public override object? VisitIterationVariable(BasicRazorParser.IterationVariableContext context)
    {
        if (context.ID().Length == 2)
        {
            ModelWrapper SingleModel = new ModelWrapper(CurrentValue);
            return SingleModel.GetPropertyValue(context.ID(1).GetText());
        }

        throw new NotImplementedException();
    }

    public override object? VisitGlobalVariable(BasicRazorParser.GlobalVariableContext context)
    {
        string result = "";
        var varName = context.ID().GetText();
        if(Variables.TryGetValue(varName, out var value))
        { 
            result = value.ToString();
        }

        return result;
    }

    public override string VisitHtmlElement(BasicRazorParser.HtmlElementContext context)
    {
        BasicRazorParser.OpeningTagContext openingTag = context.openingTag();
        BasicRazorParser.ClosingTagContext closingTag = context.closingTag();

        string tagName = openingTag.ID().ToString();
    
        string attributes = "";
        foreach (var attr in openingTag.attribute())
        {
            string attrName = attr.ID().GetText();
            string attrValue = attr.STRING().GetText();
            attributes += $" {attrName}={attrValue}";
        }
        string openingTagResult = $"<{tagName}{attributes}>";
    
        
        string contentResult = openingTagResult;
    
        
        foreach (var child in context.children)
        {
                
                var result = Visit(child);
                if (result is string )
                {
                    contentResult += result;
                }
                else if(result != null)
                {
                    contentResult += result.ToString();
                }
        }
    
        
        string closingTagResult = $"</{tagName}>";

        contentResult += closingTagResult;

        return contentResult;
    }

    public override object? VisitStatement(BasicRazorParser.StatementContext context)
    {
        var varName = context.ID().GetText();
        var value = Visit(context.expression());

        Variables[varName] = value;
        return "";
    }

    public override object? VisitConst(BasicRazorParser.ConstContext context)
    {
        if (context.INT() != null)
        {
            return int.Parse(context.GetText());
        }

        if (context.FlOAT() != null)
        {
            return float.Parse(context.GetText());
        }

        if (context.STRING() != null)
        {
            return context.GetText()[1..^1];
        }

        if (context.BOOL() != null)
        {
            return context.GetText() == "true";
        }

        if (context.NULL() != null)
        {
            return null;
        }

        throw new NotImplementedException();
    }

    
    
    public override object? VisitIdExpression(BasicRazorParser.IdExpressionContext context)
    {
        var varName = context.ID().GetText();

        if (Variables.TryGetValue(varName, out var expression))
        {
            return expression;
        } 
        throw new Exception($"variable {varName} is not defined");
    }

    public override object? VisitAdditiveExpression(BasicRazorParser.AdditiveExpressionContext context)
    {
        var left = Visit(context.expression(0));
        var right = Visit(context.expression(1));

        var mathOp = context.addOp().GetText();

        return mathOp switch
        {
            "+" => MathOperator.Add(left, right),
            "-" => MathOperator.Subtract(left, right),
            _ => throw new Exception($"Unknown operator Type: {mathOp}")
        };
    }

    public override object? VisitMultiplicativeExpression(BasicRazorParser.MultiplicativeExpressionContext context)
    {
        var left = Visit(context.expression(0));
        var right = Visit(context.expression(1));

        var mathOp = context.multOp().GetText();

        return mathOp switch
        {
            "*" => MathOperator.Multiplication(left, right),
            "/" => MathOperator.Division(left, right),
            _ => throw new Exception($"Unknown operator Type: {mathOp}")
        };
    }
    public override object? VisitComparisonExpression(BasicRazorParser.ComparisonExpressionContext context)
    {
        var left = Visit(context.expression(0));
        var right = Visit(context.expression(1));

        var compareOp = context.compareOp().GetText();

        return compareOp switch
        {
            "==" => BoolOperator.IsEqual(left, right),
            "!=" => BoolOperator.IsNotEqual(left,right),
            "<" => BoolOperator.LessThen(left,right),
            ">" => BoolOperator.GreaterThen(left, right),
            ">=" => BoolOperator.GreaterOrEqualThen(left, right),
            "<=" => BoolOperator.LessorEqualThen(left, right),
            _ => throw new Exception($"Unknown operator Type: {compareOp}")
        };
    }

    public override object? VisitBooleanExpression(BasicRazorParser.BooleanExpressionContext context)
    {
        var left = Visit(context.expression(0));
        var right = Visit(context.expression(1));

        var boolOp = context.boolOp().GetText();
        
        return boolOp switch
        {
            "&&" => BoolOperator.AndOp(left, right),
            "||" => BoolOperator.OrOp(left, right),
            _ => throw new Exception($"Unknown operator Type: {boolOp}")
        };
    }

    public override object? VisitIfStatement(BasicRazorParser.IfStatementContext context)
    {
        object? expression = Visit(context.expression());
        if (expression is bool boolexpr)
        {
            if (boolexpr)
            {
                foreach (var content in context.blockContent())
                {
                    Visit(content);
                }
            }

            return "";
        }else
            throw new Exception($"expression inside if condition must" + 
                                $" return a bool but was {context.expression().GetText()}");
    }

    public override object? VisitWhileStatement(BasicRazorParser.WhileStatementContext context)
    {
        object? expression = Visit(context.expression());
        
        if (expression is bool)
        {
            do
            {
                foreach (var content in context.blockContent())
                {
                    Visit(content);
                }
            } while ((bool)Visit(context.expression())!);
        }
        throw new Exception($"expression inside if condition must" + 
                            $" return a bool but was {context.expression().GetText()}");
    }
}